---
title: "R Notebook"
output: html_notebook
---

```{r}

#Test if BioManager is installed
if (!requireNamespace("BiocManager", quietly = TRUE)) {
  install.packages("BiocManager")
  BiocManager::install()
}

# load pacman package manager
if (!require(pacman)) {
  install.packages("pacman")
  library(pacman)
}

p_load(optparse)
p_load(tictoc)
p_load(tidyverse)
p_load(plotly)
p_load(vroom)
p_load(writexl)
p_load(ggplot2)
p_load(ggpubr)
p_load(magrittr)
p_load(knitr)
p_load(rlang)
p_load(ggrepel)

p_load(limma)
p_load(qvalue)
p_load(ruv)
p_load(mixOmics)

p_load(ProteomeRiver)
p_load(configr)
p_load(logging)
p_load(svglite)

```

## Input Parameters
```{r}

input_dir <- "/home/ignatius/PostDoc/2022/PYROXD1_BMP_13/Results/N155S/de_proteins/"
output_dir <- "/home/ignatius/PostDoc/2022/PYROXD1_BMP_13/Results/N155S/publication_graphs"

args_design_matrix_file <- "/home/ignatius/PostDoc/2022/PYROXD1_BMP_13/Source/N155S/design_matrix.tab"
args_sample_id <- "Sample_ID"

parser <- add_option(parser, "--sample_id", type = "character",
                     help = "A string describing the sample ID. This must be a column that exists in the design matrix.",
                     metavar = "string")

parser <- add_option(parser, "--replicate_group_id", type = "character",
                     help = "A string describing the replicate group ID. This must be a column that exists in the design matrix.",
                     metavar = "string")


q_val_thresh <- 0.05
top_x_gene_name <- 5

de_proteins_long_file <- "/home/ignatius/PostDoc/2022/PYROXD1_BMP_13/Results/N155S/annot_proteins/de_proteins_long_annot.tsv"



counts_rnorm.log.quant <- vroom::vroom( file.path(input_dir, "counts_after_median_scaling_and_imputation.tsv") )
counts_rnorm.log.ruvIII <- vroom::vroom( file.path(input_dir, "normalized_counts_after_ruv.tsv")  )

createDirIfNotExists(output_dir)
```

## Read Design Matrix
```{r}

design_mat_cln <- vroom::vroom(args_design_matrix_file) %>%
    as.data.frame() %>%
    dplyr::mutate(!!rlang::sym(args_sample_id) := as.character(!!rlang::sym(args_sample_id)))


rownames(design_mat_cln) <- design_mat_cln %>% pull(as.name(args_sample_id))
```

## PCA plots
```{r}

counts_rnorm.log.quant_mat <- counts_rnorm.log.quant %>%
  column_to_rownames("uniprot_acc") 

counts_rnorm.log.ruvIII_mat <- counts_rnorm.log.ruvIII %>%
  column_to_rownames("uniprot_acc") 

before_ruvIII_pca <- plotPca( counts_rnorm.log.quant_mat,
         design_matrix = design_mat_cln,
                                   sample_id_column = Sample_ID,
                                   group_column = group,
                                   title = "Before RUVIII",
         geom.text.size = 7) +
  theme(axis.text.x = element_text(size = 12))   +
  theme(axis.text.y = element_text(size = 12))  +
  theme(axis.title.x = element_text(size = 12))  +
  theme(axis.title.y = element_text(size = 12))  +
  theme(plot.title = element_text(size = 12)) +
  theme(legend.text = element_text(size = 12)) +
  theme(legend.title = element_text(size = 12))

before_ruvIII_pca



after_ruvIII_pca <- plotPca( counts_rnorm.log.ruvIII_mat,
         design_matrix = design_mat_cln,
                                   sample_id_column = Sample_ID,
                                   group_column = group,
                                   title = "After RUVIII", geom.text.size = 7) +
  theme(axis.text.x = element_text(size = 12))   +
  theme(axis.text.y = element_text(size = 12))  +
  theme(axis.title.x = element_text(size = 12))  +
  theme(axis.title.y = element_text(size = 12))  +
  theme(plot.title = element_text(size = 12)) +
  theme(legend.text = element_text(size = 12)) +
  theme(legend.title = element_text(size = 12))

after_ruvIII_pca

```


## RLE plots
```{r}

before_RUVIII_rle <- plotRle(t(as.matrix(counts_rnorm.log.quant_mat)),
        rowinfo = design_mat_cln[colnames(counts_rnorm.log.quant_mat), 
                                 "group"]) +
  theme(axis.text.x = element_text(size = 13))   +
  theme(axis.text.y = element_text(size = 13))  +
  theme(axis.title.x = element_text(size = 12))  +
  theme(axis.title.y = element_text(size = 12))  +
  theme(plot.title = element_text(size = 12)) +
  theme(legend.text = element_text(size = 12)) +
  theme(legend.title = element_text(size = 12)) +
  xlab("Samples")

before_RUVIII_rle


after_RUVIII_rle <- plotRle(t(as.matrix(counts_rnorm.log.ruvIII_mat)),
        rowinfo = design_mat_cln[colnames(counts_rnorm.log.ruvIII_mat), 
                                 "group"]) +
  theme(axis.text.x = element_text(size = 13))   +
  theme(axis.text.y = element_text(size = 13))  +
  theme(axis.title.x = element_text(size = 12))  +
  theme(axis.title.y = element_text(size = 12))  +
  theme(plot.title = element_text(size = 12)) +
  theme(legend.text = element_text(size = 12)) +
  theme(legend.title = element_text(size = 12)) +
  xlab("Samples")

after_RUVIII_rle


```


## Volcano plots
```{r}

gene_names_data <- vroom::vroom(de_proteins_long_file) %>%
  mutate(gene_name = str_split(gene_names, ":") %>% purrr::map_chr(1)) %>%
  relocate( gene_name, .before="gene_names")

show_gene_name <- gene_names_data %>%
  group_by(comparison) %>%
  arrange(comparison, q.mod) %>%
  mutate(row_id = row_number()) %>%
  ungroup()  %>%
  dplyr::filter( row_id <= top_x_gene_name & q.mod < q_val_thresh) %>%
  dplyr::select( comparison, uniprot_acc, gene_name)

selected_data <- vroom::vroom( file.path(input_dir, "lfc_qval_long.tsv") )  %>%
    mutate( lqm = -log10(q.mod))  %>%
    dplyr::mutate(colour = case_when(abs(lqm) >= 1 & q.mod >= q_val_thresh ~ "orange",
                                     abs(lqm) >= 1 & q.mod < q_val_thresh ~ "purple",
                                     abs(lqm) < 1 & q.mod < q_val_thresh ~ "blue",
                                     TRUE ~ "black")) %>%
    dplyr::mutate(colour = factor(colour, levels = c("black", "orange", "blue", "purple"))) %>%
  left_join( show_gene_name, by = c("comparison" = "comparison",
                                    "uniprot_acc" = "uniprot_acc")) %>%
  dplyr::mutate( gene_name = case_when( q.mod < q_val_thresh ~ gene_name,
                                             TRUE ~ NA_character_) )



plotOneVolcano <- function( input_data, input_title) {
  volcano_plot <-  input_data %>%
    ggplot(aes(y = lqm, x = log2FC )) +
    geom_point(aes(col = colour)) +
    scale_colour_manual(values = c(levels(selected_data$colour)),
                        labels = c(paste0("Not sig., logFC > ",
                                          1),
                                   paste0("Sig,, logFC >= ",
                                          1),
                                   paste0("Sig., logFC <",
                                          1),
                                   "Not Sign,")) +
    geom_vline(xintercept = 1, colour = "black", size = 0.2) +
    geom_vline(xintercept = -1, colour = "black", size = 0.2) +
    geom_hline(yintercept = -log10(q_val_thresh)) +
    theme_bw() +
    xlab("Log fold-change") +
    ylab(expression(-log[10] ~ q ~ value)) +
    labs(title = input_title)+  # Remove legend title
    theme(legend.title = element_blank()) +
    # theme(legend.position = "none")  +
    theme(axis.text.x = element_text(size = 13))   +
    theme(axis.text.y = element_text(size = 13))  +
    theme(axis.title.x = element_text(size = 12))  +
    theme(axis.title.y = element_text(size = 12))  +
    theme(plot.title = element_text(size = 12)) +
    theme(legend.text = element_text(size = 12)) # +
    # theme(legend.title = element_text(size = 12)) 

    volcano_plot
}


plotOneVolcanoWithGeneName <- function( input_data, input_title) {
  volcano_plot <-  input_data %>%
    ggplot(aes(y = lqm, x = log2FC, label=gene_name)) +
    geom_point(aes(col = colour)) +
    scale_colour_manual(values = c(levels(selected_data$colour)),
                        labels = c(paste0("Not sig., logFC > ",
                                          1),
                                   paste0("Sig,, logFC >= ",
                                          1),
                                   paste0("Sig., logFC <",
                                          1),
                                   "Not Sign,")) +
    geom_vline(xintercept = 1, colour = "black", size = 0.2) +
    geom_vline(xintercept = -1, colour = "black", size = 0.2) +
    geom_hline(yintercept = -log10(q_val_thresh)) +
    geom_text_repel( size  = 7, show.legend=FALSE) +
    theme_bw() +
    xlab("Log fold-change") +
    ylab(expression(-log[10] ~ q ~ value)) +
    labs(title = input_title)+  # Remove legend title
    theme(legend.title = element_blank()) +
    # theme(legend.position = "none")  +
    theme(axis.text.x = element_text(size = 13))   +
    theme(axis.text.y = element_text(size = 13))  +
    theme(axis.title.x = element_text(size = 12))  +
    theme(axis.title.y = element_text(size = 12))  +
    theme(plot.title = element_text(size = 12)) +
    theme(legend.text = element_text(size = 12)) # +
    # theme(legend.title = element_text(size = 12)) 

    volcano_plot
}

selected_data %>%
  group_by( analysis_type, comparison) %>%
  nest() %>%
  ungroup() %>%
  mutate( title = paste( analysis_type, comparison)) %>%
  mutate( plot = purrr:::map2( data, title, ~plotOneVolcano(.x, .y)) ) %>%
  pull(plot)

selected_data %>%
  group_by( analysis_type, comparison) %>%
  nest() %>%
  ungroup() %>%
  mutate( title = paste( analysis_type, comparison)) %>%
  mutate( plot = purrr:::map2( data, title, ~plotOneVolcanoWithGeneName(.x, .y)) ) %>%
  pull(plot)


```







