---
title: "R Notebook"
output: html_notebook
---



```{r}


#Test if BioManager is installed
if (!requireNamespace("BiocManager", quietly = TRUE)) {
  install.packages("BiocManager")
  BiocManager::install()
}

# load pacman package manager
if (!require(pacman)) {
  install.packages("pacman")
  library(pacman)
}

p_load(tidyverse)
p_load(plotly)
p_load(vroom)
p_load(writexl)
p_load(ggplot2)

p_load(magrittr)
p_load(xml2)
p_load(rvest)
p_load(ProteomeRiver)
p_load(httr)
p_load(stringi)
p_load(rvest)

```

```{r}
base_dir <-  here::here() 
data_dir <- file.path( base_dir, "Data")
results_dir <- file.path(base_dir, "Results")
source_dir <- file.path(base_dir, "Source")

```

```{r}
#Wen, Ruhui. (2021). Re: How i can get a list of KEGG pathways and its list of genes? . Retrieved from: https://www.researchgate.net/post/How_i_can_get_a_list_of_KEGG_pathways_and_its_list_of_genes/5ff5ff79bffe6552672ea3fc/citation/download. 

#You can retrieve the gene set from KEGG pathways of an organism using the following codes in R. Here I took Staphylcoccus aureus MRSA252 (kegg code: sar) as an example.
#step 1: install related packages and open them in R:

p_load("KEGGREST")
p_load("EnrichmentBrowser")
```


```{r}
species <- "hsa"
gene_id_to_uniprot_acc_file <- file.path(results_dir, "UniProt", "gene_ids_table_python_all.tab")
```


https://www.kegg.jp/kegg-bin/download?entry=mmu03015&format=kgml
```{r}
createDirIfNotExists(file.path( data_dir, "KEGG") )

#step2: check and obtain a list of entry identifiers (in this case: sar) and associated definition for a given database or a given set of database entries.
identifiers <- keggList(species)
saveRDS( identifiers, file.path( data_dir, "KEGG", paste0("identifiers_kegg_", species,".RDS") ) )

#step 3: download the pathways of that organism:
# /home/ignatius/.cache/R/EnrichmentBrowser
# pathways_download <- downloadPathways("mmu", out.dir= file.path( data_dir, "KEGG")) ## only use this line if you want to download all the XML files locally
pathways <- downloadPathways("mmu")
# pathways$mmu05416

#step 4: retrieve gene sets for an organism from databases such as GO and KEGG:
gene_sets <- getGenesets(org = "mmu", db = "kegg", cache = TRUE, return.type="list")
saveRDS( gene_sets, file.path( data_dir, "KEGG", paste0("gene_sets_kegg_", species,".RDS") ) )

gene_sets <- readRDS(file.path( data_dir, "KEGG", paste0("gene_sets_kegg_", species,".RDS")) )

#step5: Parse and write the gene sets to a flat text file in GMT format for other pathway enrichment analysis programs (e.g., GSEA):
writeGMT(gene_sets, gmt.file = file.path( data_dir, "KEGG", paste0("20210106_kegg_", species, "_gmt") ) )
```


## Write the list of pathways 
```{r}
pathways_list <- data.frame( pathway_id = names(pathways), 
            pathway_name = purrr::map_chr( names(pathways), ~pathways[[.]]@pathwayInfo@title))

vroom::vroom_write( pathways_list, file.path( data_dir, "KEGG", "pathways_list.tab") )


```

## Read in the UniProt Accession to Gene ID conversion table 
This table was generated by parsing the UniProt XML file 
```{r}
# need a gene_id column and pathway_id column
uniprot_acc_to_gene_id <- vroom::vroom( gene_id_to_uniprot_acc_file, col_types ="cc" )

uniprot_acc_to_gene_id
```


```{r}
gene_sets_tbl <- data.frame( pathway_id_name= names ( gene_sets )  ) %>%
  mutate( gene_id = purrr::map( pathway_id_name, ~gene_sets[[.]]) ) %>%
  unnest(gene_id) %>%
  left_join( uniprot_acc_to_gene_id, by="gene_id") %>%
  mutate( pathway_id =  str_split( pathway_id_name, pattern="_") %>% purrr::map_chr(1)) %>%
  left_join( pathways_list, by = "pathway_id") %>%
  dplyr::select(-pathway_id_name, - gene_id) %>%
  dplyr::filter(!is.na(uniprot_acc))

vroom::vroom_write( gene_sets_tbl, file.path( data_dir, "KEGG", "gene_sets.tab" ))
```





