---
title: "R Notebook"
output: html_notebook
---

```{r}
install.packages("usethis")

library(usethis)
```

```{r}
# Create a new package -------------------------------------------------
path <- file.path( "/home/ignatius/PostDoc/2021/ProteomeRiver")
create_package(path)

proj_activate(path)
#> ✓ Setting active project to '/private/var/folders/03/9x7925g54mncswxx06wpkxl00000gn/T/RtmpxLZ8U3/mypkg'
#> ✓ Changing working directory to '/var/folders/03/9x7925g54mncswxx06wpkxl00000gn/T/RtmpxLZ8U3/mypkg/'

# create_from_github("IgnatiusPang/ProteomeRiver", fork=FALSE)

use_git()

use_lgpl_license(version = 3, include_future = TRUE)
```

```{r}
use_package("tidyverse", type = "Imports", min_version = NULL)
use_package("magrittr", type = "Imports", min_version = NULL)
use_package("readxl", type = "Imports", min_version = NULL)
use_package("rlang", type = "Imports", min_version = NULL)
use_package("vroom", type = "Imports", min_version = NULL)
use_package("ggpubr", type = "Imports", min_version = NULL)
use_package("plotly", type = "Imports", min_version = NULL)
use_package("knitr", type = "Imports", min_version = NULL)

# statistical packages
use_package("limma", type = "Imports", min_version = NULL)
use_package("qvalue", type = "Imports", min_version = NULL)
use_package("ruv", type = "Imports", min_version = NULL)
use_package("mixOmics", type = "Imports", min_version = NULL)
use_package("EDASeq", type = "Imports", min_version = NULL)
use_package("RUVSeq", type = "Imports", min_version = NULL)
use_package("missMethyl", type = "Imports", min_version = NULL)

# proteomics packages
use_package("seqinr", type = "Imports", min_version = NULL)
use_package("UniProt.ws", type = "Imports", min_version = NULL)
```

```{r}
# Set up other files -------------------------------------------------
use_readme_md()
#> ✓ Writing 'README.md'

use_news_md()
#> ✓ Writing 'NEWS.md'

use_test("my-test")


# x <- 1
# y <- 2
# use_data(x, y)

# Use git ------------------------------------------------------------
use_git()
#> ✓ Initialising Git repo
#> ✓ Adding '.Rproj.user', '.Rhistory', '.Rdata', '.httr-oauth', '.DS_Store' to '.gitignore'
```

